run:
  timeout: 5m

issues:
  include:
    - EXC0001
    - EXC0005
    - EXC0011
    - EXC0012
    - EXC0013

linters:
  enable:
    - staticcheck
    - nilerr
    - errcheck
    - gosimple
    - govet
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - gosec
    - forcetypeassert
    - goconst
    - prealloc
    - predeclared
    - bodyclose
    - exportloopref
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck